USE [master]
GO

/****** Object:  Database [bwg20171_crm_bwg]    Script Date: 10.04.2017 08:22:04 ******/
CREATE DATABASE [bwg20171_crm_bwg]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bwg20171_crm_bwg_data', FILENAME = N'D:\MSSQL\bwg20171\bwg20171_crm_bwg_data.mdf' , SIZE = 4160KB , MAXSIZE = 1024000KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'bwg20171_crm_bwg_log', FILENAME = N'D:\MSSQL\bwg20171\bwg20171_crm_bwg_log.ldf' , SIZE = 1024KB , MAXSIZE = 512000KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [bwg20171_crm_bwg] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bwg20171_crm_bwg].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bwg20171_crm_bwg] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET ARITHABORT OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET  ENABLE_BROKER 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET  MULTI_USER 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bwg20171_crm_bwg] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [bwg20171_crm_bwg] SET  READ_WRITE 
GO

